# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Science for Kinesiology 
author: Hyosub Kim
copyright: 2023. This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
logo: images/NESC3505_icon.png


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 300 # Increase to a suitable value in seconds

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image

# Information about where the book exists on the web
repository:
  url: "https://github.com/hyosubkim/datasci-for-kin"  # Online location of your book
  # path_to_book:   # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  favicon: images/NESC3505_icon.png
  
# Disable building all files in book directory by default
only_build_toc_files: true
